### ISSUE TITLE
Launcher misplaced when using Arabic desktop

### ISSUE THREAD

**Issue by mhsabbagh** [pop-os/launcher#153] opened 2023-01-09 06:29 UTC
Hello.

There is a bug in the launcher application when changing the system language to Arabic. It becomes misplaced to the right side of the desktop instead of being centeralized as it is in the English desktop (See image attached).

Pop!_OS 22.04.

Happy to provide any additional information, or do any tests you want.

Regards.
![2023-01-09_09-27](https://user-images.githubusercontent.com/1293003/211251583-3da1909d-9c76-4769-9859-630825e986ca.png)

**Comment by leviport** [comment] 2023-01-09 15:52
Thanks for the report! I believe this is a duplicate of https://github.com/pop-os/shell/issues/1384

**Closed by leviport** 2023-01-09 15:52 UTC

**Comment by mhsabbagh** [comment] 2023-01-09 16:18
Thank you. You are right, will follow that one.
